var phpadsbanner = '';

phpadsbanner += '<'+'SCRIPT LANGUAGE=JavaScript> \n\nvar bnum=new Number(Math.floo';
phpadsbanner += 'r(99999999 * Math.random())+1); \n\ndocument.write(\'<'+'SCR\'+\'IPT';
phpadsbanner += ' LANGUAGE="JavaScript" \'); \n\ndocument.write(\'SRC="http://ser';
phpadsbanner += 'vedby.advertising.com/site=715682/size=160600/bnum=\'+bnum+\'/';
phpadsbanner += 'optn=1"><'+'/SCR\'+\'IPT>\'); \n\n<'+'/SCRIPT> <'+'div id="beacon_2286" st';
phpadsbanner += 'yle="position: absolute; left: 0px; top: 0px; visibility: hi';
phpadsbanner += 'dden;"><'+'img src=\'http://64.73.24.44/madison/adlog.php?banner';
phpadsbanner += 'id=2286&amp;clientid=1529&amp;zoneid=138&amp;source=&amp;blo';
phpadsbanner += 'ck=0&amp;capping=0&amp;cb=4b4ced02c731317aab4b432b8ad57a4d\' ';
phpadsbanner += 'width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\'';
phpadsbanner += '><'+'/div>';

document.write(phpadsbanner);
