var phpadsbanner = '';

phpadsbanner += '<'+'iframe src="http://view.atdmt.com/ATA/iview/ntgrebra0160000';
phpadsbanner += '226ata/direct/01?click=" frameborder="0" scrolling="no" marg';
phpadsbanner += 'inheight="0" marginwidth="0" topmargin="0" leftmargin="0" al';
phpadsbanner += 'lowtransparency="true" width="728" height="90">\n\n<'+'script lan';
phpadsbanner += 'guage="JavaScript" type="text/javascript">\n\ndocument.write(\'';
phpadsbanner += '<'+'a target=\'_blank\' href="http://64.73.24.44/madison/adclick.';
phpadsbanner += 'php?bannerid=2136&amp;zoneid=315&amp;source=&amp;dest=http%3';
phpadsbanner += 'A%2F%2Fclk.atdmt.com%2FATA%2Fgo%2Fntgrebra0160000226ata%2Fdi';
phpadsbanner += 'rect%2F01%2F&amp;ismap=" ><'+'img src="http://view.atdmt.com/AT';
phpadsbanner += 'A/view/ntgrebra0160000226ata/direct/01/"/><'+'/a>\');\n\n<'+'/script>';
phpadsbanner += '<'+'noscript><'+'a target=\'_blank\' href="http://64.73.24.44/madiso';
phpadsbanner += 'n/adclick.php?bannerid=2136&amp;zoneid=315&amp;source=&amp;d';
phpadsbanner += 'est=http%3A%2F%2Fclk.atdmt.com%2FATA%2Fgo%2Fntgrebra01600002';
phpadsbanner += '26ata%2Fdirect%2F01%2F&amp;ismap=" ><'+'img border="0" src="htt';
phpadsbanner += 'p://view.atdmt.com/ATA/view/ntgrebra0160000226ata/direct/01/';
phpadsbanner += '" /><'+'/a><'+'/noscript><'+'/iframe><'+'div id="beacon_2136" style="pos';
phpadsbanner += 'ition: absolute; left: 0px; top: 0px; visibility: hidden;"><'+'';
phpadsbanner += 'img src=\'http://64.73.24.44/madison/adlog.php?bannerid=2136&';
phpadsbanner += 'amp;clientid=1465&amp;zoneid=315&amp;source=&amp;block=0&amp';
phpadsbanner += ';capping=0&amp;cb=564b8c188b3ef482b8baad7091106e76\' width=\'0';
phpadsbanner += '\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\'><'+'/div>';

document.write(phpadsbanner);
