var phpadsbanner = '';

phpadsbanner += '<'+'object classid=\'clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\'';
phpadsbanner += ' codebase=\'http://download.macromedia.com/pub/shockwave/cabs';
phpadsbanner += '/flash/swflash.cab#version=4,0,0,0\' width=\'336\' height=\'280\'';
phpadsbanner += '><'+'param name=\'movie\' value=\'http://64.73.25.73/adserver/adim';
phpadsbanner += 'age.php?filename=20_fw1.swf&amp;contenttype=swf&amp;alink1=h';
phpadsbanner += 'ttp://64.73.25.73/adserver/adclick.php%3Fbannerid=76%26zonei';
phpadsbanner += 'd=11%26source=%26dest=http%3A%2F%2Fwww.firstweber.com%2F&ata';
phpadsbanner += 'r1=_blank\'><'+'param name=\'quality\' value=\'high\'><'+'embed src=\'ht';
phpadsbanner += 'tp://64.73.25.73/adserver/adimage.php?filename=20_fw1.swf&am';
phpadsbanner += 'p;contenttype=swf&amp;alink1=http://64.73.25.73/adserver/adc';
phpadsbanner += 'lick.php%3Fbannerid=76%26zoneid=11%26source=%26dest=http%3A%';
phpadsbanner += '2F%2Fwww.firstweber.com%2F&atar1=_blank\' quality=high width=';
phpadsbanner += '\'336\' height=\'280\' type=\'application/x-shockwave-flash\' plug';
phpadsbanner += 'inspace=\'http://www.macromedia.com/go/getflashplayer\'><'+'/embe';
phpadsbanner += 'd><'+'/object><'+'div id="beacon_76" style="position: absolute; le';
phpadsbanner += 'ft: 0px; top: 0px; visibility: hidden;"><'+'img src=\'http://64.';
phpadsbanner += '73.25.73/adserver/adlog.php?bannerid=76&amp;clientid=116&amp';
phpadsbanner += ';zoneid=11&amp;source=&amp;block=0&amp;capping=0&amp;cb=6484';
phpadsbanner += '27a8912d2b4965536a9b4a6b578f\' width=\'0\' height=\'0\' alt=\'\' st';
phpadsbanner += 'yle=\'width: 0px; height: 0px;\'><'+'/div>';

document.write(phpadsbanner);
