var phpadsbanner = '';

phpadsbanner += '<'+'script type="text/javascript" language="JavaScript">\n<'+'!--\n ';
phpadsbanner += '        google_ad_client = \'lee_416x144\';\n         google_ad';
phpadsbanner += '_width = 416;\n         google_ad_height = 144;\n         goog';
phpadsbanner += 'le_ad_format = \'416x144_new\';\n         google_safe = \'high\';';
phpadsbanner += '\n// -->\n<'+'/script>\n<'+'script type="text/javascript" language="J';
phpadsbanner += 'avaScript"\nsrc="http://pagead2.googlesyndication.com/pagead/';
phpadsbanner += 'show_ads.js"><'+'/script>\n<'+'noscript>\n    <'+'img height=1 width=1 ';
phpadsbanner += 'border=0\nsrc="http://pagead2.googlesyndication.com/pagead/im';
phpadsbanner += 'p.gif?client=ca-lee_4\n16x144&event=noscript"/>\n<'+'/noscript><'+'d';
phpadsbanner += 'iv id="beacon_474" style="position: absolute; left: 0px; top';
phpadsbanner += ': 0px; visibility: hidden;"><'+'img src=\'http://64.73.25.73/ads';
phpadsbanner += 'erver/adlog.php?bannerid=474&amp;clientid=516&amp;zoneid=117';
phpadsbanner += '&amp;source=&amp;block=0&amp;capping=0&amp;cb=90fbdf5d630770';
phpadsbanner += 'a252d4abe4ff41cc11\' width=\'0\' height=\'0\' alt=\'\' style=\'width';
phpadsbanner += ': 0px; height: 0px;\'><'+'/div>';

document.write(phpadsbanner);
