var phpadsbanner = '';

phpadsbanner += '<'+'object classid=\'clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\'';
phpadsbanner += ' codebase=\'http://download.macromedia.com/pub/shockwave/cabs';
phpadsbanner += '/flash/swflash.cab#version=5,0,0,0\' width=\'336\' height=\'280\'';
phpadsbanner += '><'+'param name=\'movie\' value=\'http://64.73.25.73/adserver/adim';
phpadsbanner += 'age.php?filename=brookfield_336x280.swf&amp;contenttype=swf&';
phpadsbanner += 'amp;alink1=http://64.73.25.73/adserver/adclick.php%3Fbanneri';
phpadsbanner += 'd=772%26zoneid=93%26source=%26dest=http%3A%2F%2Fwww.visitbro';
phpadsbanner += 'okfield.com&atar1=_blank\'><'+'param name=\'quality\' value=\'high\'';
phpadsbanner += '><'+'embed src=\'http://64.73.25.73/adserver/adimage.php?filenam';
phpadsbanner += 'e=brookfield_336x280.swf&amp;contenttype=swf&amp;alink1=http';
phpadsbanner += '://64.73.25.73/adserver/adclick.php%3Fbannerid=772%26zoneid=';
phpadsbanner += '93%26source=%26dest=http%3A%2F%2Fwww.visitbrookfield.com&ata';
phpadsbanner += 'r1=_blank\' quality=high width=\'336\' height=\'280\' type=\'appli';
phpadsbanner += 'cation/x-shockwave-flash\' pluginspace=\'http://www.macromedia';
phpadsbanner += '.com/go/getflashplayer\'><'+'/embed><'+'/object><'+'div id="beacon_772';
phpadsbanner += '" style="position: absolute; left: 0px; top: 0px; visibility';
phpadsbanner += ': hidden;"><'+'img src=\'http://64.73.25.73/adserver/adlog.php?b';
phpadsbanner += 'annerid=772&amp;clientid=732&amp;zoneid=93&amp;source=&amp;b';
phpadsbanner += 'lock=0&amp;capping=0&amp;cb=692725c07307dfb74898018d646f1723';
phpadsbanner += '\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px';
phpadsbanner += ';\'><'+'/div>';

document.write(phpadsbanner);
