document.write ('<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">\n');
document.write ('<!-- saved from url=(0057)http://www.jsonline.com/ads/ijl/l-ijl-valentines_OAS.html -->\n');
document.write ('<HTML><HEAD>\n');
document.write ('<META http-equiv=Content-Type content="text/html; charset=windows-1252">\n');
document.write ('<SCRIPT language=VBScript>\n');
document.write ('<!--\n');
document.write ('	on error resume next\n');
document.write ('	flash5VBscript=(IsObject(CreateObject("ShockwaveFlash.ShockwaveFlash.6")))\n');
document.write ('	\n');
document.write ('	widthAd=728\n');
document.write ('	heightAd=90\n');
document.write ('	\n');
document.write ('	flashFile="http://www.jsonline.com/ads/ijl/l-ijl-valentines.swf"\n');
document.write ('	URLBase="http://adserver.journalinteractive.com/RealMedia/ads/click_lx.cgi/www.jsonline.com/bym/news/nov04/273208.asp/13157/Top1/Its_Just_Lunch_Jan12-31_05_Valen/l-ijl-valentines_OAS.htm/30633837636334653431656464353030" 		\n');
document.write ('	flashFileFinal=flashFile +"?link="+URLBase+"?_RM_REDIR_="\n');
document.write ('	\n');
document.write ('	gifFile="http://www.jsonline.com/ads/ijl/l-ijl-valentines.jpg"\n');
document.write ('	\n');
document.write ('	if (flash5VBscript Eqv True) Then\n');
document.write ('		document.write ("<OBJECT classid=clsid:D27CDB6E-AE6D-11cf-96B8-444553540000 codebase=http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0 width=" & widthAd & " height=" & heightAd & ">")\n');
document.write ('		document.write ("<PARAM NAME=movie VALUE=" & flashFileFinal & ">")\n');
document.write ('		document.write ("<PARAM NAME=quality VALUE=high>")\n');
document.write ('		document.write ("<PARAM NAME=bgcolor VALUE=#FFFFFF>")\n');
document.write ('		document.write ("</OBJECT>")\n');
document.write ('	Else\n');
document.write ('		document.write ("<a href=" & URLBase & "><img src=" & gifFile & " width=" & widthAd & " height=" & heightAd & " border=0></a>")\n');
document.write ('	End If\n');
document.write ('// -->	\n');
document.write ('</SCRIPT>\n');
document.write ('\n');
document.write ('<SCRIPT language=JavaScript type=text/javascript>\n');
document.write ('<!--\n');
document.write ('	\n');
document.write ('	var widthAd=728;\n');
document.write ('	var heightAd=90;\n');
document.write ('	\n');
document.write ('	var agt=navigator.userAgent.toLowerCase();\n');
document.write ('	var isIE = (agt.indexOf("msie") != -1) ? true : false;\n');
document.write ('	var isWin = (agt.indexOf("win") != -1) ? true : false;\n');
document.write ('	var isMac = (agt.indexOf("mac")!=-1) ? true : false;\n');
document.write ('	var isOpera = (agt.indexOf("opera")!=-1) ? true : false;\n');
document.write ('	var JSflash5 = false;\n');
document.write ('\n');
document.write ('	var flashFile="http://www.jsonline.com/ads/ijl/l-ijl-valentines.swf";\n');
document.write ('	var URLBase="http://adserver.journalinteractive.com/RealMedia/ads/click_lx.cgi/www.jsonline.com/bym/news/nov04/273208.asp/13157/Top1/Its_Just_Lunch_Jan12-31_05_Valen/l-ijl-valentines_OAS.htm/30633837636334653431656464353030";		\n');
document.write ('	var flashFileFinal=flashFile +"?link="+URLBase+"?_RM_REDIR_=";\n');
document.write ('	\n');
document.write ('	gifFile="http://www.jsonline.com/ads/ijl/l-ijl-valentines.jpg";\n');
document.write ('	\n');
document.write ('	function detectFlash(){\n');
document.write ('		if (isIE==false || isWin==false || isOpera==true) {\n');
document.write ('			if (navigator.plugins){\n');
document.write ('				if (navigator.plugins["Shockwave Flash"]) {\n');
document.write ('					var flashDescription = navigator.plugins["Shockwave Flash"].description;\n');
document.write ('					var flashVersion = parseInt(flashDescription.charAt(flashDescription.indexOf(".") - 1));\n');
document.write ('					var JSflash5 = flashVersion >= 6;\n');
document.write ('					drawAds(JSflash5);\n');
document.write ('				}else{\n');
document.write ('					drawAds(JSflash5);				\n');
document.write ('				}\n');
document.write ('			}else{\n');
document.write ('				drawAds(JSflash5);\n');
document.write ('			}\n');
document.write ('		}\n');
document.write ('	}\n');
document.write ('	\n');
document.write ('	function drawAds(a) {\n');
document.write ('		if (a) {\n');
document.write ('			document.writeln("<OBJECT classid=clsid:D27CDB6E-AE6D-11cf-96B8-444553540000 codebase=http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0 width="+widthAd+" height="+heightAd+">");\n');
document.write ('		 	document.writeln("<PARAM NAME=movie VALUE="+flashFileFinal+">");\n');
document.write ('			document.writeln("<PARAM NAME=quality VALUE=high>");\n');
document.write ('		 	document.writeln("<PARAM NAME=bgcolor VALUE=#FFFFFF>");\n');
document.write ('		 	document.writeln("<EMBED src="+flashFileFinal+" quality=high bgcolor=#FFFFFF  width="+widthAd+" height="+heightAd+" TYPE=application/x-shockwave-flash PLUGINSPAGE=http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash></EMBED></OBJECT>");			\n');
document.write ('		}else{\n');
document.write ('			document.writeln("<a href="+URLBase+"><img src="+gifFile+" width="+widthAd+" height="+heightAd+" border=0></a>");\n');
document.write ('		}\n');
document.write ('	}\n');
document.write ('	\n');
document.write ('	detectFlash();\n');
document.write ('//-->\n');
document.write ('</SCRIPT>\n');
document.write ('\n');
document.write ('<META content="MSHTML 6.00.2800.1479" name=GENERATOR></HEAD>\n');
document.write ('<BODY></BODY></HTML>\n');
